import '../models/persona.dart';
import '../models/batch.dart';
import '../models/route_option.dart';

class MockDataService {
  static final List<PersonaModel> personas = [
    const PersonaModel(
      id: 'rmc',
      name: 'RMC Logistics Manager',
      tagline: 'Ready-Mix Concrete Transit Loss Prevention',
      description: 'Predict concrete slump loss, evaluate route heat/traffic exposure, and prevent rejected batches with real-time operational mitigations.',
      primaryMetrics: ['Slump Retention', 'Transit Window', 'Concrete Temp', 'Delivery Risk'],
      badgeLabel: 'Flagship Engine',
    ),
    const PersonaModel(
      id: 'health',
      name: 'Health-Conscious Users',
      tagline: 'Air Quality & Heat Vulnerability Intelligence',
      description: 'Monitor hyper-local AQI, particulate matter (PM2.5/PM10), UV radiation, and heat stress exposure windows.',
      primaryMetrics: ['AQI Index', 'PM 2.5', 'UV Index', 'Heat Exposure Risk'],
    ),
    const PersonaModel(
      id: 'fitness',
      name: 'Outdoor Fitness Enthusiasts',
      tagline: 'Optimal Training Window Predictor',
      description: 'Calculate safe running and cycling hours based on wet-bulb globe temperature, wind shear, and sudden precipitation.',
      primaryMetrics: ['Safe Running Window', 'Heat Strain', 'Wind Speed', 'Precipitation Probability'],
    ),
    const PersonaModel(
      id: 'beach',
      name: 'Beachgoers & Surfers',
      tagline: 'Coastal & Marine Safety Telemetry',
      description: 'Track high/low tide schedules, wave swell height, water surface temperature, and offshore rip-current warnings.',
      primaryMetrics: ['Tide Status', 'Swell Height', 'Water Temp', 'Wind Direction'],
    ),
    const PersonaModel(
      id: 'traveler',
      name: 'Travelers & Commuters',
      tagline: 'Corridor Weather & Highway Delay Alerts',
      description: 'Anticipate microclimate squalls, monsoon waterlogging, fog visibility drops, and airport flight delays along your journey.',
      primaryMetrics: ['Corridor Visibility', 'Rainfall Accumulation', 'Flight Weather Impact', 'Route Delay'],
    ),
    const PersonaModel(
      id: 'family',
      name: 'Parents & Families',
      tagline: 'Family Safety & School Commute Guard',
      description: 'Receive proactive alerts for sudden severe thunderstorms, extreme afternoon heat spikes, and safe pickup hours.',
      primaryMetrics: ['Commute Risk', 'Sudden Rain Alert', 'Afternoon Heat Peak', 'Air Quality Status'],
    ),
    const PersonaModel(
      id: 'agriculture',
      name: 'Agriculture & Gardeners',
      tagline: 'Crop Hydration & Microclimate Guidance',
      description: 'Evaluate root-zone soil moisture, dew point condensation, unseasonal frost probability, and irrigation advisories.',
      primaryMetrics: ['Soil Moisture %', 'Frost Probability', 'Evapotranspiration Rate', 'Rainfall Forecast'],
    ),
  ];

  static BatchModel primaryBatch204 = BatchModel(
    batchId: 'batch-rmc-204',
    batchCode: 'RMC-204',
    plantId: 'plant-001',
    plantName: 'Ahmedabad Plant 01 (Naroda)',
    projectId: 'project-007',
    projectName: 'Project Site 07 (Gift City Expansion)',
    volumeM3: 6.0,
    targetSlumpMm: 105.0,
    initialSlumpMm: 110.0,
    currentSlumpMm: 106.0,
    slumpRetentionRatio: 0.964,
    concreteTempC: 32.4,
    ambientTempC: 35.0,
    elapsedMinutes: 22.0,
    etaMinutes: 32.0,
    originalEtaMinutes: 32.0,
    distanceRemainingKm: 16.4,
    totalDistanceKm: 28.5,
    trafficIndex: 0.45,
    precipitationProb: 15.0,
    status: 'IN_TRANSIT',
    riskLevel: RiskLevel.safe,
    heatRisk: 34.0,
    travelRisk: 28.0,
    deliveryRisk: 32.0,
    compositeRisk: 31.4,
    primaryDriver: 'Transit on schedule within safe slump envelope',
    riskFactors: const [
      'Ambient temperature 35.0°C within tolerance',
      'Slump retention currently 96.4%',
      'Route A moving normally',
    ],
    recommendedAction: null,
    activeRouteId: 'route-a',
    createdAt: '2026-09-25T14:00:00Z',
  );

  static List<BatchModel> initialBatches = [
    primaryBatch204,
    BatchModel(
      batchId: 'batch-rmc-201',
      batchCode: 'RMC-201',
      plantId: 'plant-001',
      plantName: 'Ahmedabad Plant 01 (Naroda)',
      projectId: 'project-003',
      projectName: 'Project Site 03 (Sabarmati Riverfront)',
      volumeM3: 7.0,
      targetSlumpMm: 110.0,
      initialSlumpMm: 115.0,
      currentSlumpMm: 105.0,
      slumpRetentionRatio: 0.913,
      concreteTempC: 35.2,
      ambientTempC: 38.5,
      elapsedMinutes: 48.0,
      etaMinutes: 26.0,
      originalEtaMinutes: 18.0,
      distanceRemainingKm: 8.2,
      totalDistanceKm: 22.0,
      trafficIndex: 0.68,
      precipitationProb: 5.0,
      status: 'AT_RISK',
      riskLevel: RiskLevel.watch,
      heatRisk: 64.0,
      travelRisk: 58.0,
      deliveryRisk: 55.0,
      compositeRisk: 58.6,
      primaryDriver: 'Approaching safe slump threshold (91.3%)',
      riskFactors: const [
        '+8 min congestion delay on Ashram Road',
        'Concrete temp elevated at 35.2°C',
      ],
      recommendedAction: null,
      activeRouteId: 'route-201-default',
      createdAt: '2026-09-25T13:30:00Z',
    ),
    BatchModel(
      batchId: 'batch-rmc-208',
      batchCode: 'RMC-208',
      plantId: 'plant-002',
      plantName: 'Ahmedabad Plant 02 (Sanand)',
      projectId: 'project-012',
      projectName: 'Project Site 12 (Ring Road Logistics Hub)',
      volumeM3: 6.0,
      targetSlumpMm: 100.0,
      initialSlumpMm: 110.0,
      currentSlumpMm: 107.0,
      slumpRetentionRatio: 0.972,
      concreteTempC: 31.8,
      ambientTempC: 34.0,
      elapsedMinutes: 14.0,
      etaMinutes: 22.0,
      originalEtaMinutes: 22.0,
      distanceRemainingKm: 14.8,
      totalDistanceKm: 19.5,
      trafficIndex: 0.28,
      precipitationProb: 0.0,
      status: 'IN_TRANSIT',
      riskLevel: RiskLevel.safe,
      heatRisk: 28.0,
      travelRisk: 22.0,
      deliveryRisk: 25.0,
      compositeRisk: 25.0,
      primaryDriver: 'Optimal transit corridor, low temperature',
      riskFactors: const ['Nominal transit parameters'],
      recommendedAction: null,
      activeRouteId: 'route-208-default',
      createdAt: '2026-09-25T14:15:00Z',
    ),
  ];

  static List<RouteOptionModel> routesForBatch204 = [
    const RouteOptionModel(
      routeId: 'route-a',
      routeName: 'Route A (SP Ring Road via Chiloda)',
      isRecommended: false,
      etaMinutes: 61.0,
      distanceKm: 28.2,
      deliveryRisk: 78.0,
      heatRisk: 74.0,
      travelRisk: 82.0,
      trafficLevel: 'Severe Congestion (+14m delay)',
      weatherSummary: '40.2°C ambient, 68% rain cell approaching',
      tradeOffExplanation: 'Shortest distance but corridor bottleneck adds 14 min delay and causes slump retention to drop below 90%.',
      waypoints: [
        WaypointModel(lat: 23.0225, lng: 72.5714, name: 'Naroda Plant'),
        WaypointModel(lat: 23.0550, lng: 72.5950, name: 'Nana Chiloda Circle (Delay Zone)'),
        WaypointModel(lat: 23.0900, lng: 72.6100, name: 'Gift City Site 07'),
      ],
    ),
    const RouteOptionModel(
      routeId: 'route-b',
      routeName: 'Route B (Airport Bypass Expressway - Recommended)',
      isRecommended: true,
      etaMinutes: 52.0,
      distanceKm: 30.8,
      deliveryRisk: 36.0,
      heatRisk: 42.0,
      travelRisk: 30.0,
      trafficLevel: 'Free Flow (Bypass corridor)',
      weatherSummary: '35.5°C ambient, dry segment',
      tradeOffExplanation: '+2.6 km longer distance, but saves 9 minutes of transit and preserves slump retention at 94.2%.',
      waypoints: [
        WaypointModel(lat: 23.0225, lng: 72.5714, name: 'Naroda Plant'),
        WaypointModel(lat: 23.0680, lng: 72.6350, name: 'Airport Expressway Corridor'),
        WaypointModel(lat: 23.0900, lng: 72.6100, name: 'Gift City Site 07'),
      ],
    ),
    const RouteOptionModel(
      routeId: 'route-c',
      routeName: 'Route C (Old Highway via Gandhinagar)',
      isRecommended: false,
      etaMinutes: 68.0,
      distanceKm: 33.5,
      deliveryRisk: 85.0,
      heatRisk: 78.0,
      travelRisk: 89.0,
      trafficLevel: 'Urban Traffic & Surface Signals',
      weatherSummary: '39.8°C, heavy humidity',
      tradeOffExplanation: 'Excessive transit exposure exceeds 78 min safe window.',
      waypoints: [
        WaypointModel(lat: 23.0225, lng: 72.5714, name: 'Naroda Plant'),
        WaypointModel(lat: 23.0450, lng: 72.5500, name: 'Old Highway Junction'),
        WaypointModel(lat: 23.0900, lng: 72.6100, name: 'Gift City Site 07'),
      ],
    ),
  ];
}
