"""create_initial_schema

Revision ID: 9481a1c1c511
Revises: 
Create Date: 2026-09-27 20:44:54.162528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9481a1c1c511'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('organization_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('deliveries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('batch_code', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('plant_id', sa.String(), nullable=False),
    sa.Column('plant_name', sa.String(), nullable=False),
    sa.Column('plant_lat', sa.Float(), nullable=False),
    sa.Column('plant_lng', sa.Float(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('project_lat', sa.Float(), nullable=False),
    sa.Column('project_lng', sa.Float(), nullable=False),
    sa.Column('concrete_grade', sa.String(), nullable=False),
    sa.Column('volume_m3', sa.Float(), nullable=False),
    sa.Column('initial_slump_mm', sa.Float(), nullable=False),
    sa.Column('target_slump_mm', sa.Float(), nullable=False),
    sa.Column('current_slump_mm', sa.Float(), nullable=False),
    sa.Column('slump_retention_ratio', sa.Float(), nullable=False),
    sa.Column('concrete_temp_c', sa.Float(), nullable=False),
    sa.Column('ambient_temp_c', sa.Float(), nullable=False),
    sa.Column('relative_humidity', sa.Float(), nullable=False),
    sa.Column('dispatch_time', sa.String(), nullable=False),
    sa.Column('requested_delivery_time', sa.String(), nullable=True),
    sa.Column('admixture_retarder', sa.String(), nullable=True),
    sa.Column('planned_transit_minutes', sa.Float(), nullable=False),
    sa.Column('elapsed_minutes', sa.Float(), nullable=False),
    sa.Column('eta_minutes', sa.Float(), nullable=False),
    sa.Column('original_eta_minutes', sa.Float(), nullable=False),
    sa.Column('distance_remaining_km', sa.Float(), nullable=False),
    sa.Column('total_distance_km', sa.Float(), nullable=False),
    sa.Column('traffic_index', sa.Float(), nullable=False),
    sa.Column('precipitation_prob', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('active_route_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_batch_code'), 'deliveries', ['batch_code'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('delivery_outcomes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('delivery_id', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('quality_grade', sa.String(), nullable=False),
    sa.Column('site_slump_mm', sa.Float(), nullable=False),
    sa.Column('slump_variance_mm', sa.Float(), nullable=False),
    sa.Column('actual_transit_minutes', sa.Float(), nullable=False),
    sa.Column('site_concrete_temp_c', sa.Float(), nullable=False),
    sa.Column('financial_impact_inr', sa.Float(), nullable=False),
    sa.Column('financial_type', sa.String(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('ml_training_recorded', sa.Boolean(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_outcomes_delivery_id'), 'delivery_outcomes', ['delivery_id'], unique=True)
    op.create_table('delivery_risk_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('delivery_id', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('predicted_slump_mm', sa.Float(), nullable=False),
    sa.Column('slump_retention_ratio', sa.Float(), nullable=False),
    sa.Column('heat_risk', sa.Float(), nullable=False),
    sa.Column('travel_risk', sa.Float(), nullable=False),
    sa.Column('delivery_risk', sa.Float(), nullable=False),
    sa.Column('composite_risk', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('sla_status', sa.String(), nullable=False),
    sa.Column('primary_driver', sa.Text(), nullable=False),
    sa.Column('contributors', sa.JSON(), nullable=True),
    sa.Column('recommended_action', sa.String(), nullable=True),
    sa.Column('input_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_risk_results_delivery_id'), 'delivery_risk_results', ['delivery_id'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('delivery_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=False),
    sa.Column('concrete_temp_c', sa.Float(), nullable=False),
    sa.Column('drum_rpm', sa.Float(), nullable=False),
    sa.Column('current_slump_mm', sa.Float(), nullable=False),
    sa.Column('ambient_temp_c', sa.Float(), nullable=False),
    sa.Column('humidity_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_delivery_id'), 'telemetry', ['delivery_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_delivery_id'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_delivery_risk_results_delivery_id'), table_name='delivery_risk_results')
    op.drop_table('delivery_risk_results')
    op.drop_index(op.f('ix_delivery_outcomes_delivery_id'), table_name='delivery_outcomes')
    op.drop_table('delivery_outcomes')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_deliveries_batch_code'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
